### ISSUE TITLE
Checksum for a blake256 hash

### ISSUE THREAD

**Issue by cipherzzz** [cryptocoinjs/blake-hash#1]
Hello, thank you for this library... I am attempting to port a base58 address check utility from Go to js. I was wondering if your library had a checksum built into it or if you had any suggestions for how to implement such a function. thanks!

**Comment by fanatid** [comment]
You can do it with [bs58check](https://github.com/bitcoinjs/bs58check/). Original issue: https://github.com/bitcoinjs/bs58check/issues/13

**Comment by cipherzzz** [comment]
@fanatid - Thanks! Is the following the same as a double-blake256 checksum?
```
// SHA256(SHA256(buffer))
function sha256x2 (buffer) {
  var tmp = createHash('sha256').update(buffer).digest()
  return createHash('sha256').update(tmp).digest()
}
```

**Comment by fanatid** [comment]
```js
import bs58checkBase from 'bs58check/base'
import createBlakeHash from 'blake-hash'

function blake256x2 (buffer) {
  buffer = createBlakeHash('blake256').update(buffer).digest()
  return createBlakeHash('blake256').update(buffer).digest()
}

export default bs58checkBase(blake256x2)
```

**Comment by cipherzzz** [comment]
@fanatid , I can get it to work if I drop the last [4] from the decoded address' hex representation - not positive why, though?

`var createBlakeHash = require("blake-hash");
var bs58checkBase = require("bs58check/base");

function blake256x2(buffer) {
  buffer = createBlakeHash("blake256")
    .update(buffer)
    .digest();
  return createBlakeHash("blake256")
    .update(buffer)
    .digest();
}

var bs58check = bs58checkBase(blake256x2);
const bs58 = require("bs58");

function checkAddress(address, payload) {
  const bufferedPayload = Buffer.from(payload, "hex");
  const address2 = bs58check.encode(bufferedPayload, blake256x2);
  const payload2 = bs58check.decode(address, blake256x2);

  console.log("address:" + address);
  console.log("checked address:" + address2);
  console.log("payload:" + JSON.stringify(payload));
  console.log("checked payload:" + payload2.toString("hex"));
}

const address = "TsWoR2B5QhqBas1pR4YmptEKcKBJoxpTBmB";
const calcPayloadBuffer = bs58.decode(address);
const modPayloadbuffer = Buffer.from([...calcPayloadBuffer].splice(0, calcPayloadBuffer.length - 4));
checkAddress(address, modPayloadbuffer.toString("hex"));`
