### ISSUE TITLE
help,where can i get a  implementation of java

### ISSUE THREAD

**Issue by hunjixin** [cryptocoinjs/blake-hash#2]

**Comment by fanatid** [comment]
https://www.google.com/search?source=hp&ei=qLK9W975EMTqrgSW-ITwCg&q=blake+hash+java&oq=blake+hash+java&gs_l=psy-ab.3..0i22i30k1.1530.5157.0.5456.14.13.0.0.0.0.141.1059.7j4.11.0....0...1c.1.64.psy-ab..3.11.1057...0j0i131k1j0i10k1j0i10i30k1j0i13k1j0i13i30k1j0i30k1.0.nNecGrggeTE
